CREATE TABLE IF NOT EXISTS "order" (
  "orderId" VARCHAR(20) PRIMARY KEY,
  value NUMERIC(10, 2) NOT NULL,
  "creationDate" TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS items (
  id SERIAL PRIMARY KEY,
  "orderId" VARCHAR(20) REFERENCES "order"("orderId"),
  "productId" VARCHAR(20) NOT NULL,
  quantity INTEGER NOT NULL,
  price NUMERIC(10, 2) NOT NULL
);